name: Cloudflare Production Deployment
on:
  push:
    branches:
      - cloudflare
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: build hoyodecrimen website
        run: >
          docker run -v ${{github.workspace}}:/hoyodecrimen node:20.14.0
          /bin/sh -c 'npm install 
          && ./node_modules/.bin/gatsby telemetry --disable 
          && ./node_modules/.bin/gatsby build 
          && chmod -R o+rwx /hoyodecrimen'
     
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT }}
          directory: public
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: cloudflare
          # Optional: Change the working directory
          workingDirectory: ${{github.workspace}}/public
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'
