name: Netlify Production Deployment
on:
  push:
    branches:
      - netlify

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Deploy-Netlify-Production:
    name: deploy to netlify
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: build hoyodecrimen website
        env:
          NETLIFY_SITE_ID: 15a82f5a-5dd0-4b52-afeb-9e17b03dc075
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: >
          docker run -v ${ GITHUB_WORKSPACE }:/hoyodecrimen node:20.14.0
          /bin/sh -c 'cd /hoyodecrimen
          && npm install
          && npm install netlify-cli@17.10.1 -g
          && ./node_modules/.bin/gatsby telemetry --disable
          && ./node_modules/.bin/gatsby build
          && netlify deploy --dir=public --auth ${ NETLIFY_API_TOKEN } --prod'
